Chats = new Mongo.Collection('chats');
Positions= new Mongo.Collection('positions');
Recruiters = new Mongo.Collection('recruiters');
Seekers = new Mongo.Collection('seekers');
Companies = new Mongo.Collection('companies');
Interviews = new Mongo.Collection('interviews');
Referals = new Mongo.Collection('referals');
Offers = new Mongo.Collection('offers');
Skills = new Mongo.Collection('skills');